"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronLeft,
  ChevronRight, CircleUserRound, Clock3, FilePenLine, Layers3, LockKeyhole,
  Menu, Plus, RotateCcw, Search, Sparkles, UploadCloud, X, Zap,
} from "lucide-react";
import { BlogPost, blogPosts, categories, formatDate, formatShortDate } from "@/lib/blog-data";

type Theme = "detective" | "magician";
type View = "home" | "blog" | "categories" | "calendar" | "admin";

const navItems: { label: string; href: string; icon: typeof BookOpen }[] = [
  { label: "首页", href: "/", icon: Sparkles },
  { label: "文章", href: "/blog", icon: BookOpen },
  { label: "分类", href: "/categories", icon: Layers3 },
  { label: "时间线", href: "/calendar", icon: CalendarDays },
];

function ThemeToggle({ theme, onToggle }: { theme: Theme; onToggle: () => void }) {
  const detective = theme === "detective";
  return <button className="theme-toggle" onClick={onToggle} aria-label={detective ? "切换到魔术模式" : "切换到推理模式"}><span className="theme-icon">{detective ? "🎀" : "🎩"}</span><span className="theme-toggle-copy"><small>主题</small><strong>{detective ? "推理模式" : "魔术模式"}</strong></span><span className="theme-switch"><span /></span></button>;
}

function SiteHeader({ theme, onToggle, menuOpen, onMenu }: { theme: Theme; onToggle: () => void; menuOpen: boolean; onMenu: () => void }) {
  const pathname = usePathname();
  return <header className="site-header"><Link href="/" className="brand" aria-label="东海档案馆首页"><span className="brand-mark"><span>东</span><i /></span><span className="brand-copy"><strong>东海档案馆</strong><small>DETECTIVE DIARY / ARCHIVE</small></span></Link><nav className={`main-nav ${menuOpen ? "is-open" : ""}`} aria-label="主导航">{navItems.map(({ label, href, icon: Icon }) => { const active = pathname === href; return <Link key={href} href={href} className={`nav-link ${active ? "is-active" : ""}`} aria-current={active ? "page" : undefined}><Icon size={17} strokeWidth={1.8} />{label}</Link>; })}</nav><div className="header-actions"><div className="header-search"><Search size={16} /><span>搜索文章...</span></div><Link href="/admin" className={`login-link ${pathname === "/admin" ? "is-active" : ""}`} aria-current={pathname === "/admin" ? "page" : undefined}><CircleUserRound size={16} /> 关于我</Link><ThemeToggle theme={theme} onToggle={onToggle} /><button className="mobile-menu" onClick={onMenu} aria-label={menuOpen ? "关闭菜单" : "打开菜单"}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>;
}

function PostCard({ post, featured = false, onOpen }: { post: BlogPost; featured?: boolean; onOpen?: (post: BlogPost) => void }) {
  return <article className={`post-card ${featured ? "post-card-featured" : ""} accent-${post.accent}`}><div className={`post-thumb ${featured ? "has-hero" : ""}`} style={featured ? { backgroundImage: "url('/hero-archive.png')" } : undefined}><span className="thumb-case">CASE {post.id.replace("case-", "")}</span><span className="thumb-symbol">{post.type === "技术" ? "♠" : post.pinned ? "🎀" : "✦"}</span><span className="thumb-stamp">{post.pinned ? "置顶" : post.type}</span></div><div className="post-card-content"><div className="post-card-topline"><span className="eyebrow"><span className="eyebrow-dot" />{post.category}</span>{post.pinned && <span className="pin-badge">置顶档案</span>}</div><h3>{post.title}</h3><p>{post.excerpt}</p><div className="tag-list">{post.tags.slice(0, 4).map((tag) => <span key={tag}>#{tag}</span>)}</div><div className="post-card-footer"><div className="post-meta"><span><Clock3 size={13} /> {formatShortDate(post.date)}</span><span><span className="mini-eye">◉</span> {post.readTime}</span></div><button className="read-more" onClick={() => onOpen?.(post)}>阅读全文 <ArrowUpRight size={15} /></button></div></div></article>;
}

function MiniCalendar({ posts, onOpen }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void }) {
  const days = Array.from({ length: 30 }, (_, i) => i + 1);
  const postDays = new Map(posts.map((post) => [Number(post.date.slice(-2)), post]));
  return <div className="mini-calendar"><div className="mini-calendar-head"><strong>柯南日历</strong><span>2026 年 9 月</span><div><ChevronLeft size={14} /><ChevronRight size={14} /></div></div><div className="mini-week">{["一", "二", "三", "四", "五", "六", "日"].map((day) => <span key={day}>{day}</span>)}</div><div className="mini-days">{days.map((day) => { const post = postDays.get(day); return <button key={day} className={post ? "has-note" : ""} onClick={() => post && onOpen(post)} disabled={!post}>{day}{post && <i />}</button>; })}</div></div>;
}

function ProfileCard() {
  return <div className="profile-card"><div className="profile-head"><div className="profile-avatar">东</div><div><span>ABOUT THE AUTHOR</span><strong>东海</strong><small>记录生活的观察员</small></div><span className="profile-bow">🎀</span></div><p>“如果你的话，一定能找到真相的。”</p><div className="profile-stats"><span><strong>03</strong>文章</span><span><strong>03</strong>分类</span><span><strong>09</strong>标签</span></div></div>;
}

function Sidebar({ posts, onOpen }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void }) {
  return <aside className="right-sidebar"><ProfileCard /><div className="sidebar-panel"><div className="sidebar-title"><strong>热门分类</strong><span>INDEX</span></div><div className="hot-categories">{categories.map((category) => <Link key={category.name} href={`/categories#${category.name}`}><span>{category.symbol}</span><strong>{category.name}</strong><small>{category.count}</small></Link>)}</div></div><div className="sidebar-panel"><div className="sidebar-title"><strong>最新标签</strong><span>TAG CLOUD</span></div><div className="cloud-tags">{["日常", "技术", "随笔", "架构", "夜晚", "慢生活", "Next.js", "记录"].map((tag) => <span key={tag}>#{tag}</span>)}</div></div><MiniCalendar posts={posts} onOpen={onOpen} /></aside>;
}

function HomeView({ posts, onOpen, theme }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void; theme: Theme }) {
  const featured = posts.find((post) => post.pinned) ?? posts[0];
  return <><section className={`home-hero ${theme === "magician" ? "hero-day-mode" : "hero-night-mode"}`}><img className={`hero-image hero-night ${theme === "detective" ? "is-active" : ""}`} src="/hero-archive.png" alt="月光下的原创侦探与魔术主题城市背景" /><img className={`hero-image hero-day ${theme === "magician" ? "is-active" : ""}`} src="/hero-archive-day.png" alt="阳光下的原创魔术主题城市背景" /><div className="hero-overlay" /><div className="hero-hero-copy"><span className="hero-kicker">TRUTH IS ONLY ONE / PERSONAL BLOG</span><h1>真相只有一个！</h1><p>记录日常，也记录那些尚未结案的想法。</p><span className="hero-signature">— 东海 / EAST SEA</span></div><div className="hero-case-card"><span>ARCHIVE NO. 001</span><strong>生活 · 技术 · 灵感</strong><small>Welcome to my detective diary</small></div></section><div className="home-content-grid"><main className="home-feed"><div className="feed-title"><div><span className="section-kicker">LATEST CASE FILES</span><h2>最新文章</h2></div><Link href="/blog" className="text-link">查看全部 <ArrowUpRight size={15} /></Link></div>{featured && <PostCard post={featured} featured onOpen={onOpen} />}<div className="feed-label"><span>RECENT NOTES</span><span>{posts.length.toString().padStart(2, "0")} ENTRIES</span></div>{posts.filter((post) => post.id !== featured?.id).map((post) => <PostCard key={post.id} post={post} onOpen={onOpen} />)}</main><Sidebar posts={posts} onOpen={onOpen} /></div></>;
}

function BlogView({ posts, onOpen }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void }) {
  const [query, setQuery] = useState(""); const filtered = posts.filter((post) => `${post.title} ${post.excerpt} ${post.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="page-view"><div className="page-intro"><div><span className="section-kicker">CASE FILES / ALL ENTRIES</span><h1>文章</h1><p>生活与技术的时间切片，按日期整理保存。</p></div><div className="page-intro-number">{posts.length.toString().padStart(2, "0")}<small>ENTRIES</small></div></div><div className="search-bar"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题、摘要或标签" /><span>⌘ K</span></div><div className="blog-list">{filtered.map((post) => <PostCard key={post.id} post={post} onOpen={onOpen} />)}</div>{!filtered.length && <div className="empty-state"><Search size={24} /><strong>没有找到匹配档案</strong><span>换一个关键词试试看。</span></div>}</section>;
}

function CategoriesView({ posts, onOpen }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void }) {
  const [selected, setSelected] = useState<string | null>(null); const visible = selected ? posts.filter((post) => post.category === selected) : posts;
  return <section className="page-view"><div className="page-intro"><div><span className="section-kicker">INDEX / CATEGORIES</span><h1>分类</h1><p>按兴趣整理，找到同一条思路的不同回声。</p></div></div><div className="category-grid">{categories.map((category) => <button key={category.name} className={`category-card ${selected === category.name ? "is-selected" : ""}`} onClick={() => setSelected(selected === category.name ? null : category.name)}><span className="category-symbol">{category.symbol}</span><span className="category-card-top"><span>CAT / {category.name}</span><span>{category.count.toString().padStart(2, "0")}</span></span><strong>{category.name}</strong><p>{category.description}</p><ArrowUpRight size={17} /></button>)}</div><div className="section-heading compact"><div><span className="section-kicker">{selected ? `FILTERED / ${selected}` : "ALL CATEGORIES"}</span><h2>相关档案</h2></div></div><div className="post-grid">{visible.map((post) => <PostCard key={post.id} post={post} onOpen={onOpen} />)}</div></section>;
}

function CalendarView({ posts, onOpen }: { posts: BlogPost[]; onOpen: (post: BlogPost) => void }) {
  const [month, setMonth] = useState(new Date(2026, 8, 1)); const first = new Date(month.getFullYear(), month.getMonth(), 1); const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const leading = (first.getDay() + 6) % 7; const postByDay = new Map(posts.map((post) => [post.date, post])); const cells = Array.from({ length: leading + days }, (_, index) => index < leading ? null : index - leading + 1); const monthLabel = new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "long" }).format(month);
  return <section className="page-view"><div className="page-intro"><div><span className="section-kicker">TIMELINE / MONTHLY INDEX</span><h1>时间线</h1><p>在时间里查看每一次记录发生的日期。</p></div></div><div className="calendar-layout"><div className="calendar-card"><div className="calendar-header"><div><span className="section-kicker">FIELD NOTES</span><h2>{monthLabel}</h2></div><div className="calendar-controls"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="上个月"><ChevronLeft size={17} /></button><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="下个月"><ChevronRight size={17} /></button></div></div><div className="weekdays">{["一", "二", "三", "四", "五", "六", "日"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map((day, index) => { const dateKey = day ? `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}` : ""; const post = dateKey ? postByDay.get(dateKey) : undefined; return <button key={`${dateKey}-${index}`} className={`calendar-cell ${post ? "has-post" : ""} ${day ? "" : "is-empty"}`} onClick={() => post && onOpen(post)} disabled={!post}>{day && <><span>{day}</span>{post && <i title={post.title} />}</>}</button>; })}</div></div><aside className="calendar-aside"><span className="section-kicker">THIS MONTH</span><div className="calendar-total"><strong>{posts.filter((post) => post.date.startsWith(`${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}`)).length}</strong><span>篇记录</span></div><div className="timeline-mini">{posts.slice(0, 3).map((post) => <button key={post.id} onClick={() => onOpen(post)}><span>{formatShortDate(post.date)}</span><strong>{post.title}</strong></button>)}</div></aside></div></section>;
}

function ArticleView({ post, onBack, theme }: { post: BlogPost; onBack: () => void; theme: Theme }) {
  return <section className="article-view"><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> 返回文章列表</button><div className="article-header"><span className="section-kicker">CASE {post.id.replace("case-", "")} / {post.type.toUpperCase()}</span><h1>{post.title}</h1><p>{post.excerpt}</p><div className="article-meta"><span>{formatDate(post.date)}</span><span className="meta-divider" /><span><Clock3 size={14} /> {post.readTime}</span><span className="article-author">东海 · 作者</span></div></div><div className="article-art" style={{ backgroundImage: `url('${theme === "detective" ? "/hero-archive.png" : "/hero-archive-day.png"}')` }}><span>FIELD NOTE / {post.category}</span><strong>{post.type === "技术" ? "♠" : post.pinned ? "🎀" : "✦"}</strong><small>ARCHIVE / EAST SEA</small></div><div className="article-body">{post.content.map((paragraph, index) => <p key={index}>{paragraph}</p>)}<div className="article-note"><Zap size={16} /><div><strong>档案备注</strong><span>这是一条来自写作者的现场记录。</span></div></div></div><div className="article-tags">{post.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div></section>;
}

function AdminView({ posts, onSave, onReset }: { posts: BlogPost[]; onSave: (post: BlogPost) => void; onReset: () => void }) {
  const [editing, setEditing] = useState<BlogPost | null>(null); const [title, setTitle] = useState(""); const [excerpt, setExcerpt] = useState(""); const [category, setCategory] = useState("日常生活"); const [type, setType] = useState<"生活" | "技术">("生活"); const [body, setBody] = useState(""); const [saved, setSaved] = useState(false);
  const openEditor = (post?: BlogPost) => { const target = post ?? { id: `case-${Date.now()}`, slug: "", title: "", excerpt: "", category: "日常生活", type: "生活" as const, date: new Date().toISOString().slice(0, 10), readTime: "5 分钟", tags: ["新记录"], accent: "crimson" as const, content: [] }; setEditing(target); setTitle(target.title); setExcerpt(target.excerpt); setCategory(target.category); setType(target.type); setBody(target.content.join("\n\n")); setSaved(false); };
  const save = () => { if (!title.trim() || !editing) return; const post: BlogPost = { ...editing, title: title.trim(), excerpt: excerpt.trim() || "一条新的现场记录。", category, type, content: body.split(/\n\s*\n/).filter(Boolean), slug: editing.slug || title.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-") || `entry-${Date.now()}` }; onSave(post); setSaved(true); setEditing(null); };
  return <section className="page-view admin-view"><div className="page-intro"><div><span className="section-kicker">PRIVATE CONSOLE / SINGLE ACCOUNT</span><h1>编辑后台</h1><p>这是你的私人写作入口。</p></div><div className="auth-status"><CircleUserRound size={17} /><span>已登录</span><strong>东海</strong></div></div><div className="admin-toolbar"><div className="admin-state"><span className="status-dot" /> 本地预览模式 · 内容保存在当前浏览器</div><div className="admin-actions"><button className="button button-quiet" onClick={onReset}><RotateCcw size={15} /> 恢复示例内容</button><button className="button button-primary" onClick={() => openEditor()}><Plus size={16} /> 新建文章</button></div></div><div className="admin-list">{posts.map((post) => <div className="admin-row" key={post.id}><div className="admin-row-symbol">{post.type === "技术" ? "♠" : "🎀"}</div><div className="admin-row-copy"><span>{post.category} · {formatDate(post.date)}</span><strong>{post.title}</strong></div><div className="admin-row-status">{post.pinned && <span className="pin-badge">置顶</span>}<span className="published"><Check size={13} /> 已发布</span></div><button className="icon-button" onClick={() => openEditor(post)} aria-label={`编辑${post.title}`}><FilePenLine size={17} /></button></div>)}</div>{editing && <div className="editor-overlay"><div className="editor-modal"><div className="editor-header"><div><span className="section-kicker">{editing.title ? "EDIT ENTRY" : "NEW ENTRY"}</span><h2>{editing.title ? "编辑档案" : "写下新档案"}</h2></div><button className="icon-button" onClick={() => setEditing(null)} aria-label="关闭编辑器"><X size={19} /></button></div><label>标题<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="给这条记录一个标题" /></label><label>摘要<textarea value={excerpt} onChange={(event) => setExcerpt(event.target.value)} rows={2} placeholder="用一句话概括这条记录" /></label><div className="editor-two-col"><label>类型<select value={type} onChange={(event) => setType(event.target.value as "生活" | "技术")}><option>生活</option><option>技术</option></select></label><label>分类<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></div><label>正文<textarea className="body-input" value={body} onChange={(event) => setBody(event.target.value)} rows={8} placeholder="写下你的记录，段落之间空一行" /></label><div className="upload-box"><UploadCloud size={20} /><div><strong>拖入图片或选择封面</strong><span>接入云端存储后可直接上传 JPG、PNG、WEBP</span></div><button className="button button-quiet" type="button">选择图片</button></div><div className="editor-footer"><span>{saved ? "已保存" : "草稿会在发布后立即上线"}</span><div><button className="button button-quiet" onClick={() => setEditing(null)}>取消</button><button className="button button-primary" onClick={save}><Check size={15} /> 保存并发布</button></div></div></div></div>}{saved && <div className="toast"><Check size={16} /> 文章已发布到博客</div>}</section>;
}

export default function BlogApp({ initialView = "home", initialTheme = "magician" }: { initialView?: View; initialTheme?: Theme }) {
  const pathname = usePathname();
  const view: View = pathname === "/" ? "home" : pathname === "/blog" ? "blog" : pathname === "/categories" ? "categories" : pathname === "/calendar" ? "calendar" : pathname === "/admin" ? "admin" : initialView;
  const [theme, setTheme] = useState<Theme>(initialTheme); const [menuOpen, setMenuOpen] = useState(false); const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null); const [posts, setPosts] = useState<BlogPost[]>(blogPosts);
  useEffect(() => { const storedPosts = window.localStorage.getItem("east-sea-posts"); if (storedPosts) { try { setPosts(JSON.parse(storedPosts)); } catch { /* keep examples */ } } }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; window.localStorage.setItem("east-sea-theme", theme); document.cookie = `east-sea-theme=${theme}; path=/; max-age=31536000; samesite=lax`; }, [theme]);
  useEffect(() => { setSelectedPost(null); setMenuOpen(false); }, [pathname]);
  const orderedPosts = useMemo(() => [...posts].sort((a, b) => Number(Boolean(b.pinned)) - Number(Boolean(a.pinned)) || b.date.localeCompare(a.date)), [posts]);
  const openPost = (post: BlogPost) => { setSelectedPost(post); setMenuOpen(false); };
  const savePost = (post: BlogPost) => { const next = posts.some((item) => item.id === post.id) ? posts.map((item) => item.id === post.id ? post : item) : [post, ...posts]; setPosts(next); window.localStorage.setItem("east-sea-posts", JSON.stringify(next)); };
  const resetPosts = () => { setPosts(blogPosts); window.localStorage.removeItem("east-sea-posts"); };
  return <div className="site-shell"><SiteHeader theme={theme} onToggle={() => setTheme(theme === "detective" ? "magician" : "detective")} menuOpen={menuOpen} onMenu={() => setMenuOpen(!menuOpen)} /><div className="app-body"><main className={`site-main ${view === "home" ? "home-main" : ""}`}>{selectedPost ? <ArticleView post={selectedPost} theme={theme} onBack={() => setSelectedPost(null)} /> : view === "home" ? <HomeView posts={orderedPosts} theme={theme} onOpen={openPost} /> : view === "blog" ? <BlogView posts={orderedPosts} onOpen={openPost} /> : view === "categories" ? <CategoriesView posts={orderedPosts} onOpen={openPost} /> : view === "calendar" ? <CalendarView posts={orderedPosts} onOpen={openPost} /> : <AdminView posts={orderedPosts} onSave={savePost} onReset={resetPosts} />}</main></div><footer className="site-footer"><span>© 2026 EAST SEA ARCHIVE</span><span>KEEP THE CLUE / KEEP THE NOTE</span><span className="footer-links"><Link href="/admin">PRIVATE CONSOLE</Link><span>·</span><span>ORIGINAL FAN-INSPIRED DESIGN</span></span></footer></div>;
}
